[project]
name = "mindtrace-models"
version = "0.1.0"
description = "Models for Mindtrace"
license = {text = "Apache-2.0"}
authors = [
    {name = "Mindtrace Team"}
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "mindtrace-core",
    "mindtrace-registry",
    "mindtrace-services"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
