// This file will be auto-generated by openapi-typescript
// when the backend is ready. For now, we define mock types.

// Example: When backend is ready, run:
// npx openapi-typescript http://localhost:8000/openapi.json -o ./lib/api/types.ts

export interface ApiResponse {
  status: string;
  message: string;
  timestamp: string;
}
