[project]
name = "mindtrace-apps"
version = "0.1.0"
dependencies = [
    "mindtrace-core",
    "mindtrace-registry",
    "mindtrace-database",
    "mindtrace-services",
    "mindtrace-datalake",
    "mindtrace-models",
    "mindtrace-cluster",
    "mindtrace-jobs",
    "mindtrace-hardware",
    "mindtrace-ui",
    "mindtrace-automation",
    # Reflex app dependencies
    "reflex<=0.7.14",
    "fastapi>=0.110.0",
    "uvicorn>=0.27.1",
    "sqlmodel>=0.0.16",
    "python-multipart>=0.0.9",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "pydantic-settings>=2.9.1",
]

[tool.setuptools]
packages = ["mindtrace.apps"]

[tool.setuptools.package-dir]
"" = "."

[tool.dstool.scripts]
reflex-dev = "cd mindtrace/apps/mindtrace/apps/reflex-app && reflex run"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
