# Run inspectra in the end
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir inspectra

# Launch the inspectra app with `uv run python -m inspectra.launch()`
CMD ["uv", "run", "python", "-m", "inspectra.launch()"]
