"""Models for CameraManagerService API."""

from mindtrace.hardware.api.cameras.models.requests import (
    # Backend & Discovery
    BackendFilterRequest,
    BandwidthLimitCameraRequest,
    # Network & Bandwidth
    BandwidthLimitRequest,
    CameraCloseBatchRequest,
    CameraCloseRequest,
    CameraConfigureBatchRequest,
    # Configuration
    CameraConfigureRequest,
    CameraOpenBatchRequest,
    # Camera Lifecycle
    CameraOpenRequest,
    CameraQueryRequest,
    CaptureBatchRequest,
    CaptureHDRBatchRequest,
    CaptureHDRRequest,
    # Image Capture
    CaptureImageRequest,
    ConfigFileExportRequest,
    ConfigFileImportRequest,
    # Specific Parameters
    ExposureRequest,
    GainRequest,
    ImageEnhancementRequest,
    InterPacketDelayRequest,
    PacketSizeRequest,
    PixelFormatRequest,
    ROIRequest,
    # Streaming
    StreamStartRequest,
    StreamStatusRequest,
    StreamStopRequest,
    TriggerModeRequest,
    WhiteBalanceRequest,
)
from mindtrace.hardware.api.cameras.models.responses import (
    ActiveCamerasResponse,
    ActiveStreamsResponse,
    # Backend & Discovery
    BackendInfo,
    BackendInfoResponse,
    BackendsResponse,
    BandwidthSettings,
    BandwidthSettingsResponse,
    # Base Responses
    BaseResponse,
    BatchCaptureResponse,
    BatchHDRCaptureResponse,
    BatchOperationResponse,
    # Batch Operations
    BatchOperationResult,
    BoolResponse,
    CameraCapabilities,
    CameraCapabilitiesResponse,
    CameraConfiguration,
    CameraConfigurationResponse,
    # Camera Information
    CameraInfo,
    CameraInfoResponse,
    CameraStatus,
    CameraStatusResponse,
    CaptureResponse,
    # Capture Operations
    CaptureResult,
    # Configuration Files
    ConfigFileOperationResult,
    ConfigFileResponse,
    DictResponse,
    # Error Handling
    ErrorDetail,
    ErrorResponse,
    FloatResponse,
    HDRCaptureResponse,
    HDRCaptureResult,
    IntResponse,
    ListResponse,
    NetworkDiagnostics,
    NetworkDiagnosticsResponse,
    # Parameter Ranges
    ParameterRange,
    RangeResponse,
    # Streaming
    StreamInfo,
    StreamInfoResponse,
    StreamStatus,
    StreamStatusResponse,
    StringResponse,
    # System & Network
    SystemDiagnostics,
    SystemDiagnosticsResponse,
)

__all__ = [
    # Requests
    "BackendFilterRequest",
    "CameraOpenRequest",
    "CameraOpenBatchRequest",
    "CameraCloseRequest",
    "CameraCloseBatchRequest",
    "CameraConfigureRequest",
    "CameraConfigureBatchRequest",
    "CameraQueryRequest",
    "ConfigFileImportRequest",
    "ConfigFileExportRequest",
    "CaptureImageRequest",
    "CaptureBatchRequest",
    "CaptureHDRRequest",
    "CaptureHDRBatchRequest",
    "BandwidthLimitRequest",
    "ExposureRequest",
    "GainRequest",
    "ROIRequest",
    "TriggerModeRequest",
    "PixelFormatRequest",
    "WhiteBalanceRequest",
    "ImageEnhancementRequest",
    "BandwidthLimitCameraRequest",
    "PacketSizeRequest",
    "InterPacketDelayRequest",
    "StreamStartRequest",
    "StreamStopRequest",
    "StreamStatusRequest",
    # Responses
    "BaseResponse",
    "BoolResponse",
    "StringResponse",
    "IntResponse",
    "FloatResponse",
    "ListResponse",
    "DictResponse",
    "BackendInfo",
    "BackendsResponse",
    "BackendInfoResponse",
    "CameraInfo",
    "CameraStatus",
    "CameraCapabilities",
    "CameraConfiguration",
    "CameraInfoResponse",
    "CameraStatusResponse",
    "CameraCapabilitiesResponse",
    "CameraConfigurationResponse",
    "ActiveCamerasResponse",
    "CaptureResult",
    "CaptureResponse",
    "BatchCaptureResponse",
    "HDRCaptureResult",
    "HDRCaptureResponse",
    "BatchHDRCaptureResponse",
    "SystemDiagnostics",
    "SystemDiagnosticsResponse",
    "BandwidthSettings",
    "BandwidthSettingsResponse",
    "NetworkDiagnostics",
    "NetworkDiagnosticsResponse",
    "BatchOperationResult",
    "BatchOperationResponse",
    "ErrorDetail",
    "ErrorResponse",
    "ParameterRange",
    "RangeResponse",
    "ConfigFileOperationResult",
    "ConfigFileResponse",
    "StreamInfo",
    "StreamStatus",
    "StreamInfoResponse",
    "StreamStatusResponse",
    "ActiveStreamsResponse",
]
