[project]
name = "mindtrace-core"
version = "0.1.0"
dependencies = [
    "pillow>=11.2.1",
    "pydantic>=2.11.1",
    "tqdm>=4.67.1",
    "urllib3>=2.2.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
