[project]
name = "mindtrace-storage"
version = "0.1.0"
dependencies = [
    "google-auth>=2.40.3",
    "google-cloud-storage",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
