[project]
name = "mindtrace-services"
version = "0.1.0"
dependencies = [
    "mindtrace-core",
    "structlog>=24.4.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
