[project]
name = "mindtrace-services"
version = "0.1.0"
dependencies = [
    "mindtrace-core",
]

[tool.setuptools]
packages = ["mindtrace.services"]

[tool.setuptools.package-dir]
"" = "."

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
