[project]
name = "mindtrace-services"
version = "0.1.0"
dependencies = [
    "gunicorn>=23.0.0",
    "httpx>=0.27.2",
    "mindtrace-core",
    "structlog>=24.4.0",
    "uvicorn>=0.34.3",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
