[project]
name = "mindtrace-models"
version = "0.1.0"
dependencies = [
    "numpy",
    "mindtrace-core"
]

[tool.setuptools]
packages = ["mindtrace.models"]

[tool.setuptools.package-dir]
"" = "."

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"