# Auto-Proportion Image Downloader Configuration

# Database queries
database_queries:
  query_type: "get_images_by_date"

# Google Cloud Storage settings
gcp:
  bucket: ""
  credentials_file: "

sampling:
  
  cameras:
    camx:
      proportion: 0.6
      number: 100
    camy:
      proportion: 0.4


start_date: "2025-06-30"
end_date: "2025-07-01"

# Random seed for reproducible sampling (optional)
seed: 42

download_path: "" 
max_workers: 8 

# Weights Information
task_name: # Registered task name in the model registry
version: # Version of the task
inference_list:
  zone_segmentation: "mask" # Export type for the zone segmentation task
  spatter_segmentation: "mask" # Export type for the spatter segmentation task

# Output settings
output_folder: # Folder to save the output
threshold: 0.4 # Threshold for the inference. Currently unused
save_visualizations: True # Whether to save the visualizations