name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - main
      - feature/ci-test
  push:
    branches:
      - dev
      - main
      - feature/ci-test
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Print UV version
        run: |
          uv --version

      - name: Sync dependencies
        run: |
          uv sync --dev --all-extras

      - name: Ensure ds-run is installed
        run: |
          uv tool install ds-run

      - name: Show ds-run version
        run: |
          ds --version

      - name: Show Docker Compose version
        run: |
          docker compose version || docker-compose version

      - name: Run tests
        env:
          PY_COLORS: "1"
        run: |
          . .venv/bin/activate
          pwd && ls -calF && which python3 && which pytest
          bash scripts/run_tests.sh --unit
